/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interpreter;

import org.junit.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.*;

public class LexerTest {

    @Test
    public void testLexerIdentAndInt() {
        String program = "(add (mult 2 3) 4)";
        List<Token> expectedTokens = Arrays.asList(
                new PlainToken(TokenType.LPAREN),
                new DataToken(TokenType.IDENTIFIER, "add"),
                new PlainToken(TokenType.LPAREN),
                new DataToken(TokenType.IDENTIFIER, "mult"),
                new DataToken(TokenType.INT_LITERAL, "2"),
                new DataToken(TokenType.INT_LITERAL, "3"),
                new PlainToken(TokenType.RPAREN),
                new DataToken(TokenType.INT_LITERAL, "4"),
                new PlainToken(TokenType.RPAREN)
        );

        List<Token> actualTokens = new Lexer(program).tokens();
        assertEquals(expectedTokens, actualTokens);
    }
}
